apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{.Values.clusterIssuer.name}}
spec:
  acme:
    email: {{.Values.contactInfo.email}}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{.Values.clusterIssuer.privateKeySecretRef.name}}
    solvers:
    - http01:
        ingress:
          class: {{.Values.ingress.ingressClass}}