stages:
    - image-push
    - setup-runner-stage
    - app-deployment

### image-push ###

build-image:
    stage: image-push
    tags:
      - image-dialler
    script:
      - echo "Building image ..."
      - docker build -t $IMAGE_NAME:$IMAGE_VERSION .
      - echo "Done"
    allow_failure: true
    rules:
      - if: '$SKIP_BUILD == "true"'
        when: never


tag-image:
    stage: image-push
    tags:
      - image-dialler
    script:
      - echo "Tagging image ..."
      - docker tag $IMAGE_NAME:$IMAGE_VERSION $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_VERSION
      - echo "Done"
    # rules:
    #   - if: '$SKIP_BUILD == "true"'
    #     when: never

push-image:
    stage: image-push
    tags:
      - image-dialler
    script:
      - echo "Logging in to Docker Registry ..."
      - echo "$DR_USER_PASSWD" | docker login $DOCKER_REGISTRY --username $DR_USER_NAME --password-stdin
      - echo "Pushing image ..."
      - docker push $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_VERSION
      - echo "Logging out from Docker Registry ..."
      - docker logout $DOCKER_REGISTRY
      - echo "Done"
    allow_failure: true
    # rules:
    #   - if: '$SKIP_BUILD == "true"'
    #     when: never
        
### setup-runner-stage ###

install-python:
  tags: 
    - registry-runner
  stage: setup-runner-stage
  script:
    - whoami
    - echo "Installing python"
    - sudo  apt-get update
    - sudo  apt-get install -y python3
    - echo "Installed"

install-pip:
  tags: 
    - registry-runner
  stage: setup-runner-stage
  script:
    - echo "Installing pip"
    - sudo  apt-get update
    - sudo  apt-get install -y python3-pip
    - echo "Installed"

install-ansible:
  tags: 
    - registry-runner
  stage: setup-runner-stage
  script:
    - echo "Installing ansible"
    - sudo  pip install ansible
    - echo "Installed"

install-sshpass:
  tags: 
    - registry-runner
  stage: setup-runner-stage
  script:
    - echo "Installing sshpass"
    - sudo  apt-get update
    - sudo  apt-get install -y sshpass
    - echo "Installed"

copy-file:
  tags: 
    - registry-runner
  stage: setup-runner-stage
  script:
    - echo "Making keys dir"
    - sudo  mkdir /keys || true
    - echo "Done"

copy-keys:
  tags: 
    - registry-runner
  stage: setup-runner-stage
  script:
    - echo "Copy keys"
    - sudo cp ./id_rsa /keys/rsa_id
    - cd /keys
    - sudo chown gitlab-runner:gitlab-runner /keys 
    - sudo echo $GITLAB_RUNNER_PUBKEY > rsa_id.pub
    - sudo chown gitlab-runner:gitlab-runner /keys/rsa_id
    - echo "Done"

### app-deployment ###

app-deployment:
    stage: app-deployment
    tags:
      - registry-runner
    script:
      - echo "Launch ansible role called deploy_app"
      - cd ansible
      - ansible-playbook tasks-for-deploy_app-arch.yml -e 
            "
              ansible_become_pass=$ROOT_PASSWORD 
              app_container=$APP_CONTAINER   
              app_port_ext=$APP_PORT_EXT
              app_version=$APP_VERSION
              password=$ROOT_PASSWORD
              dr_username=$DR_USER_NAME
              dr_password=$DR_USER_PASSWD
              dr_port_ext=$DOCKER_REGISTRY_PORT_EXT                
              docker_registry=$DOCKER_REGISTRY
              image_name=$IMAGE_NAME        
              image_tag=$IMAGE_VERSION     
              network_name=$NETWORK_NAME
            "
      - sudo rm /keys/* || true
      - echo "App deployed"

###192.168.1.100:5000