apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eugenetask-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: www.registrypao.run.place/sabsternal
    targetRevision: 0.1.0
    chart: eugenetask
    helm:
      valueFiles:
        - values.yaml 
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true