- name: Deploy docker on client1ubuntu
  become: true
  hosts: client2ubuntu
  
  tasks:
    - name: Copy install_docker.sh to target
      copy:
        src: ./install_docker.sh
        dest: /tmp/install_docker.sh
        mode: '0777'