- name: Deploy docker on client1ubuntu
  become: true
  hosts: client1ubuntu
  
  tasks:
    - name: Copy install_docker.sh to target
      copy:
        src: ./install_docker.sh
        dest: /tmp/install_docker.sh
        mode: '0777'

    - name: Run the Docker installation script
      command: /tmp/install_docker.sh

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes
      

