name: Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Current pos
        run: |
          sudo pwd
          sudo ls -la

      - name: Set up JQ
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Update version
        id: version
        run: |
          CURRENT_VERSION=$(cat charts/${{ secrets.CHART_DIR }}/Chart.yaml | grep 'version:' | awk '{print $2}')
          echo "NEW_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          set -e
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.ORG_NAME }}/${{ secrets.IMAGE_NAME }}:${{ env.NEW_VERSION }} .

      - name: Push Docker image
        run: |
          set -e
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.ORG_NAME }}/${{ secrets.IMAGE_NAME }}:${{ env.NEW_VERSION }}

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Build Helm chart
        run: |
          helm package charts/${{ secrets.CHART_DIR }}

      - name: Login Helm to private repository
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | helm registry login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 

      - name: Push Helm chart to private repository
        run: |
          helm push charts/${{ secrets.CHART_DIR }}/${{ secrets.CHART_NAME }}-${{ env.NEW_VERSION }}.tgz oci://${{ secrets.DOCKER_REGISTRY }}/${{ secrets.ORG_NAME }}