apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.dockerSecret.name}}
  namespace: {{.Values.namespace}}
data:
  .dockerconfigjson: {{.Values.dockerSecret.dockerconfigjson}}
type: kubernetes.io/dockerconfigjson